### ISSUE TITLE
Allow deletion of multiple items at once

### ISSUE THREAD

**Issue by ColtenBerry** [404thecomputer/budget-buddy#11]
Right now, many items can be added using the frequency feature. However, if a user wanted to delete that item and all of the items added because of the frequency feature, it would be a very tedious process. Allowing many items to be deleted at once, or allowing for the deletion of all frequency items in a single delete would benefit the user.

**Comment by LHJohnston** [comment]
I'd like to try and fix this issue

**Comment by mgoadric** [comment]
@ColtenBerry don't forget to close the issue when the pull request is merged!
