### ISSUE TITLE
Have the app keep track of total balance

### ISSUE THREAD

**Issue by ColtenBerry** [404thecomputer/budget-buddy#8]
Maybe this app could also keep track of a user's total balance. So when an item is added, it is marked as an income or expense, and the balance will be updated automatically or whenever the user marks the bill as "paid"

**Comment by dylcarinc** [comment]
I would like to work on this issue.

**Comment by mgoadric** [comment]
@ColtenBerry don't forget to close the issue when the pull request is merged!
